<a href="https://colab.research.google.com/github/gowrithampi/deeplearning_with_pytorch/blob/main/deep_learning_with_pytorch_chapter4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#### Mount google drive 
from google.colab import drive
drive.mount('/content/gdrive')


Mounted at /content/gdrive


In [ ]:
#### clone directories from github

%cd /content/gdrive/My Drive/pytorch_manning/dlwpt-code
#!git clone https://github.com/deep-learning-with-pytorch/dlwpt-code


/content/gdrive/My Drive/pytorch_manning/dlwpt-code


In [ ]:
## python list 
l = [9,8,7]


Unlike Python lists, python tensors are allocated to contiguous blocks of memory

In [ ]:
import torch
## one dimensional tensor filled with ones
a = torch.ones(3)

In [ ]:
a

tensor([1., 1., 1.])

In [ ]:
a[0]

tensor(1.)

In [ ]:
## output it as float
float(a[0])

1.0

In [ ]:
## constructing a pytorch tensor from a list
points_1d = torch.tensor([1,2,3,4,5,6])
## to construct a 2 d tensor, pass a list of lists to the tensor's constructor
points_2d = torch.tensor([[1.0,1.2] , [1.2 , 3.4] , [5.6, 6.5]])

In [ ]:
## to access the first element in the 2-d tensor. This output will be a 1d tensor. 
points_2d[0]
## to access the 2nd element of the first element of the tensor
points_2d[0,1]

tensor(1.2000)

In [ ]:
a = points_2d.shape

NameError: ignored

In [ ]:
## suppose we have a 5*5 picture with 3 channels and 2 batches 

batch_t = torch.randn(2,3,5,5)

## taking the mean along the 3rd tensor dimension from the right
batch_t.mean(-3) 

print(batch_t)

tensor([[[[-0.9773,  1.4250, -1.3201, -0.5273, -2.2023],
          [-0.6055,  0.8450, -1.0017,  1.3321, -1.3654],
          [ 0.9472, -1.9854, -0.6317, -0.3784,  1.0319],
          [ 0.4777,  1.0885,  0.0394,  0.0055,  0.1230],
          [-0.4966, -0.3350,  0.8077,  1.3668, -0.2839]],

         [[-1.4443, -0.4858, -1.1872,  0.7070,  0.9138],
          [ 2.4818, -1.0848, -1.1361, -0.4019, -0.8737],
          [ 1.2885, -0.6379, -0.4118, -0.4548,  3.0535],
          [ 0.7134,  1.0152,  0.1129, -0.3949, -2.0509],
          [ 0.2123,  2.5653,  0.9393, -0.3367,  0.8056]],

         [[-0.7379, -1.0691, -0.6892,  1.2069, -1.3313],
          [-1.7851, -0.0343,  0.5463,  2.1284,  0.9937],
          [-0.7129,  0.7520, -1.2223,  0.5588, -0.4709],
          [ 0.7252,  1.4658, -0.3595, -1.2834,  1.9744],
          [-0.4128, -0.4119,  0.5171, -0.5711,  2.1154]]],


        [[[ 0.3747,  0.1423,  1.4013, -0.9045,  1.0288],
          [-0.2887, -0.1017, -0.4922, -1.3476, -0.6939],
          [-0.0497,  1.

In [ ]:
## let us try a weighted mean 
# weights = torch.tensor([0.2126,0.7152,0.722])
weights = torch.tensor([2,2,2])
print(weights.shape)
## we do not need to add the first dimension because pytorch adds it automatically
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)
print(unsqueezed_weights.shape)
batch_t*unsqueezed_weights

torch.Size([3])
torch.Size([3, 1, 1])


tensor([[[[-1.9547,  2.8501, -2.6402, -1.0545, -4.4046],
          [-1.2110,  1.6900, -2.0035,  2.6641, -2.7307],
          [ 1.8943, -3.9707, -1.2634, -0.7567,  2.0638],
          [ 0.9553,  2.1770,  0.0787,  0.0110,  0.2461],
          [-0.9933, -0.6701,  1.6154,  2.7335, -0.5678]],

         [[-2.8886, -0.9717, -2.3744,  1.4141,  1.8277],
          [ 4.9637, -2.1697, -2.2722, -0.8038, -1.7474],
          [ 2.5770, -1.2758, -0.8235, -0.9096,  6.1070],
          [ 1.4268,  2.0303,  0.2259, -0.7898, -4.1017],
          [ 0.4246,  5.1306,  1.8787, -0.6734,  1.6112]],

         [[-1.4757, -2.1382, -1.3783,  2.4138, -2.6626],
          [-3.5701, -0.0685,  1.0927,  4.2568,  1.9874],
          [-1.4257,  1.5039, -2.4446,  1.1175, -0.9419],
          [ 1.4504,  2.9315, -0.7190, -2.5668,  3.9489],
          [-0.8256, -0.8238,  1.0343, -1.1422,  4.2308]]],


        [[[ 0.7493,  0.2845,  2.8026, -1.8091,  2.0576],
          [-0.5775, -0.2034, -0.9844, -2.6953, -1.3877],
          [-0.0994,  3.

In [ ]:
## note that stride of an index is obtained by multiplying the dimensions that follow the index
print(batch_t.stride())
batch_t.shape

(75, 25, 5, 1)


torch.Size([2, 3, 5, 5])

In [ ]:
x = torch.tensor([[3,2],[5,1]])
x_t = x.transpose(0,1)
print(x.storage(), x_t.storage())
x[0] = 5



In [ ]:
### copy a cpu tensor to the GPU 
#x_gpu = x.to(device = 'cuda')

In [ ]:
#x_gpu.device

In [ ]:
############### Real world Data with Pytorch, Chapter 4, Practice

In [ ]:
import imageio

In [ ]:
## read in an image using image IO 
%ls data/p1ch4/image-dog
img_arr = imageio.imread('data/p1ch4/image-dog/bobby.jpg')

## note that the default shape puts the channel as the last element
img_arr.shape

bobby.jpg


(720, 1280, 3)

In [ ]:
## create a pytorch tensor with the image array 
img = torch.from_numpy(img_arr)
## we permute, so that channel comes first, the way pytorch likes it
out = img.permute(2,0,1)
out.shape
## Underlying storage doesn't change
#img.storage()[100] == out.storage()[100]

torch.Size([3, 720, 1280])

In [ ]:
### reading a series of images, pre allocate a tensor

batch_size = 3
batch = torch.zeros(batch_size, 3, 256, 256, dtype = torch.uint8) ##uint8 is used in most photographic formats to represent color

## read images one by one 

import os

data_dir = 'data/p1ch4/image-cats'

filenames = [ name for name in os.listdir(data_dir) if name.split('.')[1] == 'png']
for i, name in enumerate(filenames) : 
  image_path = data_dir + '/'+ name
  img = torch.from_numpy(imageio.imread(image_path)).permute(2,0,1)
  ## retaining only the first three channels, even if more exist
  img = img[0:3]
  batch[i] = img
  




In [ ]:
### normalizing image data 
## typecast to float
batch = batch.float()

## calculate this to do the normalization using a for loop, I'm trying to avoid
## a for loop for my own learning
n_channels = batch.size()[1]
print(n_channels)

## by collapsing all other dimensions, I get the mean for each channel
## by usind keepdim = True, I retain the dimensions of the tensor
##so normalization is easily applicable by broadcasting

mean = batch.mean(dim = [0,2,3], keepdim = True)
std = batch.std(dim = [0,2,3], keepdim = True)

batch = (batch - mean)/std








3


In [ ]:
## Understanding the scatter function in pytorch 

indices  = torch.tensor([1,2,3,6])
source = torch.tensor([8,9,10,100,101,200,300], dtype = torch.float32)
destination = torch.zeros(8)

## the elements of the source tensor 
## are sent to the the destination tensor
## at the indices specified by the indices tensor
destination.scatter(0,indices,source)

## the source tensor could also be a scalar

## How can this be used to perform one hot encoding
## consider a tensor representing three distinct classes
classes = torch.tensor([1,1,1,0,0,0,1,2,1,1,2,2])
source = 1
destination = torch.zeros(12,3)

## the _ makes it an inplace function, the tensor is modified in place
destination.scatter_(1,classes.unsqueeze(1), 1)




tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 1.]])

In [ ]:
## Working with the pytorch wine dataset

import csv
import numpy as np

wine_path = 'data/p1ch4/tabular-wine/winequality-white.csv'

## in the textbook csv.reader was used to read column names
## and numpy's loadtxt was used to read the numerical data
## I'd think pandas is a much better option to do both together
col_names = next(csv.reader(open(wine_path), delimiter = ';')) 
wine_numpy = np.loadtxt(wine_path, dtype = np.float32, delimiter = ";", skiprows = 1)
wineq = torch.from_numpy(wine_numpy) 

## second step: separating the dataset into the input data and target variables
## data is everything except the last column
data = wineq[:, :-1]

## target is just the last column
## we convert it to long because the scatter function requires int64 for indices
target = wineq[:,-1].long()

## one hot encode the target based on the technique above
target_onehot = torch.zeros(data.size()[0], len(col_names))
target_onehot.scatter_(1,target.unsqueeze(1),1.0)

## find mean and standard deviation in a vectorized manner 
## dim here is the dimension to collapse, so the metric is 
## calculated along the dimensions not in dim 
mean = data.mean(dim = 0, keepdim = True)
std_dev = data.std(dim = 0, keepdim= True)

## normalize the wine data
data = (data - mean) / std_dev



torch.Size([4898, 12])


In [ ]:
## Exploratory data analysis 
## 1. Text book : How do we tell apart good and bad wines ?
## calculations here are done with normalized data, unlike the textbook
## I feel this makes it easier to visualize relative merits/demerits


bad_indices = target <= 3
bad_indices.shape , bad_indices.dtype , bad_indices.sum()

#brackets are necessary here, otherwise & will take precedence
#I've spent countless hours debuggint this issue
med_indices = (target >=3) & (target<7)
good_indices = target >= 7

## boolean indexing, the boolean tensor bad_indices is used to filter the bad_wines dataset
## data points where the index has value True are retained, the others discarded
bad_wines = data[bad_indices]
medium_wines = data[med_indices]
good_wines = data[good_indices]

## calculate means separately for each of the wine types, and display 
bad_wines_mean = bad_wines.mean(dim = 0)
medium_wines_mean = medium_wines.mean(dim = 0)
good_wines_mean = good_wines.mean(dim = 0)


## zip creates tuples of means for each characteristic of bad, medium and good quality wines
for i, means in enumerate( zip(col_names, bad_wines_mean, medium_wines_mean, good_wines_mean)): 
  print("{:1} {:40}  {:6.2f} {:6.2f}  {:6.2f} ".format(i, *means))
  



0 fixed acidity                               0.88   0.04   -0.15 
1 volatile acidity                            0.55   0.04   -0.13 
2 citric acid                                 0.01   0.02   -0.07 
3 residual sugar                              0.00   0.06   -0.22 
4 chlorides                                   0.39   0.10   -0.35 
5 free sulfur dioxide                         1.06   0.01   -0.04 
6 total sulfur dioxide                        0.76   0.09   -0.31 
7 density                                     0.29   0.15   -0.54 
8 pH                                         -0.01  -0.05    0.18 
9 sulphates                                  -0.13  -0.02    0.09 
10 alcohol                                    -0.14  -0.20    0.73 


In [ ]:
## simple thresholding model on tota sulfur dioxide
## calculate std deviations separately for each of the wine types, and display 
bad_wines_std = bad_wines.std(dim = 0)
medium_wines_std = medium_wines.std(dim = 0)
good_wines_std = good_wines.std(dim = 0)

bad_wines_metrics, medium_wines_metrics, good_wines_metrics = zip( bad_wines_mean, bad_wines_std) , zip(medium_wines_mean, medium_wines_std) , zip(good_wines_mean, good_wines_std)

print("{:2} {:45} {:12} {:12} {:12}".format("N", "colname" , "bad" , "medium" , "good" ))
## zip creates tuples of means for each characteristic of bad, medium and good quality wines
for i, metrics in enumerate( zip(col_names, bad_wines_metrics, medium_wines_metrics, good_wines_metrics)):
  colname, bad_metrics, medium_metrics, good_metrics = metrics[0] , metrics[1], metrics[2], metrics[3]
  
  print("{:2} {:40}  {:6.2f}{:6.2f} , {:6.2f}{:6.2f}, {:6.2f}{:6.2f}".format(i, colname , *bad_metrics, *medium_metrics, *good_metrics))


 



N  colname                                       bad          medium       good        
 0 fixed acidity                               0.88  2.04 ,   0.04  1.02,  -0.15  0.91
 1 volatile acidity                            0.55  1.40 ,   0.04  1.01,  -0.13  0.93
 2 citric acid                                 0.01  0.67 ,   0.02  1.07,  -0.07  0.66
 3 residual sugar                              0.00  1.05 ,   0.06  1.03,  -0.22  0.85
 4 chlorides                                   0.39  2.13 ,   0.10  1.08,  -0.35  0.51
 5 free sulfur dioxide                         1.06  4.08 ,   0.01  1.05,  -0.04  0.81
 6 total sulfur dioxide                        0.76  2.54 ,   0.09  1.04,  -0.31  0.77
 7 density                                     0.29  0.95 ,   0.15  0.97,  -0.54  0.93
 8 pH                                         -0.01  1.39 ,  -0.05  0.98,   0.18  1.04
 9 sulphates                                  -0.13  1.05 ,  -0.02  0.95,   0.09  1.17
10 alcohol                                

In [ ]:
 

## Considering the data, I choose a threshold for density that can act as a classifer
## lets try 1 std dev below the mean 

threshold = good_wines_mean[7] - 1*good_wines_std[7]

predicted_good_indices = data[:,7] < threshold

print(threshold)

print(sum(good_indices))
print(sum(predicted_good_indices))
print(target[(good_indices == False) & (predicted_good_indices == True) ])
print(sum(torch.logical_and(good_indices, predicted_good_indices)))

## Evaluate the precision of this model 
print(sum(torch.logical_and(good_indices, predicted_good_indices))/ sum(predicted_good_indices))

## Evaluate the recall 
print(sum(torch.logical_and(good_indices, predicted_good_indices))/ sum(good_indices))

## Note the poor precision and recall, to have my best bet at precision, I chose density because it had the lowest variability

tensor(-1.4668)
tensor(1060)
tensor(254)
tensor([6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6,
        6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 6, 5, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 5, 6, 6, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 6, 6, 6, 6, 6, 6, 6, 6])
tensor(138)
tensor(0.5433)
tensor(0.1302)


Time series data: Case Study: Analyzing Washington DC's bike sharing system's hourly count of rental bikes. 

In [ ]:
## Read in data

bike_path = 'data/p1ch4/bike-sharing-dataset/hour-fixed.csv'
## a dictionary is the input to converters, the dictionary contains functions to convert the column to a number
bikes_numpy = np.loadtxt(fname = bike_path, dtype = np.float32, skiprows = 1, delimiter = ",", converters= {1 : lambda x: float(x[8:10])})


